language: node_js

node_js:
  - "node"

install:
  - npm i
  - npm i -g codecov
  - npm i -g codacy-coverage

script:
  - npm run report-coverage
  - codecov
  - cat ./coverage/lcov.info | codacy-coverage
